SCOPING_MODEL_NAME = "openai:gpt-4.1-mini"
SCOPING_TEMPERATURE = 0.8

RESEARCH_AGENT_MODEL_NAME = "openai:gpt-4.1-mini"
RESEARCH_SUMMARIZATION_MODEL_NAME = "openai:gpt-4.1-mini"
RESEARCH_COMPRESS_MODEL_NAME = "openai:gpt-4.1-mini"
RESEARCH_COMPRESS_MAX_TOKENS = 32000
# 单次 Tavily 搜索每个 query 返回的条数（工具 / talivy_search_multiple 默认值）
TAVILY_MAX_RESULTS = 3
MAX_SEARCH_ITERATIONS = 15
# Tavily 去重后按 URL 可信度过滤的下限（0–100）；全低于此值时仍保留分数最高的一条
CREDIBILITY_MIN_SCORE = 40

SUPERVISOR_MODEL_NAME = "gpt-4.1-mini"
MAX_RESEARCHER_ITERATIONS = 5
MAX_CONCURRENT_RESEARCHERS = 3

FINAL_REPORT_MODEL_NAME = "openai:gpt-4.1-mini"
FINAL_REPORT_MAX_TOKENS = 32000

DEFAULT_RECURSION_LIMIT = 50
